In [11]:
import pandas as pd
from google.colab import files
import io

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

  # Read the CSV file into a pandas DataFrame, specifying the tab delimiter
  df = pd.read_csv(io.StringIO(uploaded[fn].decode('utf-8')), sep='\t')
  display(df.head())

Saving DB_3.csv to DB_3 (2).csv
User uploaded file "DB_3 (2).csv" with length 32287 bytes

,user_id\t,age,gender,occupation,work_mode,screen_time_hours\t,work_screen_hours,leisure_screen_hours,sleep_hours,sleep_quality_1_5,stress_level_0_10,productivity_0_100\t,exercise_minutes_per_week,social_hours_per_week,mental_wellness_index_0_100,Unnamed: 15
0,U0001,33,Female,Employed,Remote,10.79,5.44,5.35,6.63,1.0,9.3,44.7,127,0.7,9.3,NaN
1,U0002,28,Female,Employed,In-person,7.40,0.37,7.03,8.05,3.0,5.7,78.0,74,2.1,56.2,NaN
2,U0003,35,Female,Employed,Hybrid,9.78,1.09,8.69,6.48,1.0,9.1,51.8,67,8.0,3.6,NaN
3,U0004,42,Male,Employed,Hybrid,11.13,0.56,10.57,6.89,1.0,10.0,37.0,0,5.7,0.0,NaN
4,U0005,28,Male,Student,Remote,13.22,4.09,9.13,5.79,1.0,10.0,38.5,143,10.1,0.0,NaN

# Task
Perform data preprocessing on the uploaded dataset according to the provided algorithm, including data cleaning, type conversion, feature selection, scaling, and splitting, adding comments to explain each step.

## Загрузка данных

### Subtask:
Убедитесь, что данные загружены в pandas DataFrame.

**Reasoning**:
Check if the variable `df` exists and is a pandas DataFrame, then display the head and info of the dataframe.

In [12]:
import pandas as pd

if 'df' in globals() and isinstance(df, pd.DataFrame):
    print("DataFrame 'df' loaded successfully.")
    display(df.head())
    df.info()
else:
    print("DataFrame 'df' not found or is not a pandas DataFrame.")

DataFrame 'df' loaded successfully.

,user_id\t,age,gender,occupation,work_mode,screen_time_hours\t,work_screen_hours,leisure_screen_hours,sleep_hours,sleep_quality_1_5,stress_level_0_10,productivity_0_100\t,exercise_minutes_per_week,social_hours_per_week,mental_wellness_index_0_100,Unnamed: 15
0,U0001,33,Female,Employed,Remote,10.79,5.44,5.35,6.63,1.0,9.3,44.7,127,0.7,9.3,NaN
1,U0002,28,Female,Employed,In-person,7.40,0.37,7.03,8.05,3.0,5.7,78.0,74,2.1,56.2,NaN
2,U0003,35,Female,Employed,Hybrid,9.78,1.09,8.69,6.48,1.0,9.1,51.8,67,8.0,3.6,NaN
3,U0004,42,Male,Employed,Hybrid,11.13,0.56,10.57,6.89,1.0,10.0,37.0,0,5.7,0.0,NaN
4,U0005,28,Male,Student,Remote,13.22,4.09,9.13,5.79,1.0,10.0,38.5,143,10.1,0.0,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   user_id	                     398 non-null    object
 1   age                          400 non-null    int64
 2   gender                       397 non-null    object
 3   occupation                   399 non-null    object
 4   work_mode                    398 non-null    object
 5   screen_time_hours	           398 non-null    float64
 6   work_screen_hours            397 non-null    float64
 7   leisure_screen_hours         399 non-null    float64
 8   sleep_hours                  400 non-null    float64
 9   sleep_quality_1_5            398 non-null    float64
 10  stress_level_0_10            399 non-null    float64
 11  productivity_0_100	          400 non-null    float64
 12  exercise_minutes_per_week    400 non-null    int64
 13  social_hours_per_week        400 non-null    float64
 14  mental_wellness_index_0_100  398 non-null    float64
 15  Unnamed: 15                  0 non-null      float64
dtypes: float64(10), int64(2), object(4)
memory usage: 50.1+ KB

## Очистка данных

### Subtask:
Обработайте пропущенные значения и некорректные данные.

**Reasoning**:
Examine the DataFrame for missing values, drop the column with only missing values, and clean the column names by removing leading/trailing spaces or special characters.

In [13]:
# Examine missing values
print("Missing values per column:")
print(df.isnull().sum())

# Drop the 'Unnamed: 15' column
df = df.drop('Unnamed: 15', axis=1)
print("\nDataFrame after dropping 'Unnamed: 15' column:")
display(df.head())

# Clean column names
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace('\t', '')
print("\nCleaned column names:")
print(df.columns)

Missing values per column:
user_id\t                        2
age                              0
gender                           3
occupation                       1
work_mode                        2
screen_time_hours\t              2
work_screen_hours                3
leisure_screen_hours             1
sleep_hours                      0
sleep_quality_1_5                2
stress_level_0_10                1
productivity_0_100\t             0
exercise_minutes_per_week        0
social_hours_per_week            0
mental_wellness_index_0_100      2
Unnamed: 15                    400
dtype: int64

DataFrame after dropping 'Unnamed: 15' column:

,user_id\t,age,gender,occupation,work_mode,screen_time_hours\t,work_screen_hours,leisure_screen_hours,sleep_hours,sleep_quality_1_5,stress_level_0_10,productivity_0_100\t,exercise_minutes_per_week,social_hours_per_week,mental_wellness_index_0_100
0,U0001,33,Female,Employed,Remote,10.79,5.44,5.35,6.63,1.0,9.3,44.7,127,0.7,9.3
1,U0002,28,Female,Employed,In-person,7.40,0.37,7.03,8.05,3.0,5.7,78.0,74,2.1,56.2
2,U0003,35,Female,Employed,Hybrid,9.78,1.09,8.69,6.48,1.0,9.1,51.8,67,8.0,3.6
3,U0004,42,Male,Employed,Hybrid,11.13,0.56,10.57,6.89,1.0,10.0,37.0,0,5.7,0.0
4,U0005,28,Male,Student,Remote,13.22,4.09,9.13,5.79,1.0,10.0,38.5,143,10.1,0.0

Cleaned column names:
Index(['user_id', 'age', 'gender', 'occupation', 'work_mode',
       'screen_time_hours', 'work_screen_hours', 'leisure_screen_hours',
       'sleep_hours', 'sleep_quality_1_5', 'stress_level_0_10',
       'productivity_0_100', 'exercise_minutes_per_week',
       'social_hours_per_week', 'mental_wellness_index_0_100'],
      dtype='object')

**Reasoning**:
Analyze the unique values and their frequencies in the `occupation` and `work_mode` columns to identify any inconsistencies or incorrect entries that might need cleaning or standardization.

In [14]:
# Analyze unique values and their frequencies in 'occupation'
print("Unique values and frequencies in 'occupation' column:")
print(df['occupation'].value_counts())

# Analyze unique values and their frequencies in 'work_mode'
print("\nUnique values and frequencies in 'work_mode' column:")
print(df['work_mode'].value_counts())

Unique values and frequencies in 'occupation' column:
occupation
Employed         206
Student          107
Self-employed     45
Unemployed        27
Retired           14
Name: count, dtype: int64

Unique values and frequencies in 'work_mode' column:
work_mode
Remote       148
Hybrid       146
In-person    104
Name: count, dtype: int64

## Преобразование типов данных

### Subtask:
Преобразуйте строковые значения в числовые, если это необходимо для алгоритмов машинного обучения.

**Reasoning**:
Identify and convert categorical columns to numerical using one-hot encoding.

In [15]:
# Identify columns with object data types
object_columns = df.select_dtypes(include=['object']).columns
print(f"Object columns to convert: {list(object_columns)}")

# Apply one-hot encoding to categorical columns
df = pd.get_dummies(df, columns=object_columns, drop_first=True)

# Display the first few rows of the updated DataFrame
display(df.head())

Object columns to convert: ['user_id', 'gender', 'occupation', 'work_mode']

,age,screen_time_hours,work_screen_hours,leisure_screen_hours,sleep_hours,sleep_quality_1_5,stress_level_0_10,productivity_0_100,exercise_minutes_per_week,social_hours_per_week,...,user_id_U0399,user_id_U0400,gender_Male,gender_Non-binary/Other,occupation_Retired,occupation_Self-employed,occupation_Student,occupation_Unemployed,work_mode_In-person,work_mode_Remote
0,33,10.79,5.44,5.35,6.63,1.0,9.3,44.7,127,0.7,...,False,False,False,False,False,False,False,False,False,True
1,28,7.40,0.37,7.03,8.05,3.0,5.7,78.0,74,2.1,...,False,False,False,False,False,False,False,False,True,False
2,35,9.78,1.09,8.69,6.48,1.0,9.1,51.8,67,8.0,...,False,False,False,False,False,False,False,False,False,False
3,42,11.13,0.56,10.57,6.89,1.0,10.0,37.0,0,5.7,...,False,False,True,False,False,False,False,False,False,False
4,28,13.22,4.09,9.13,5.79,1.0,10.0,38.5,143,10.1,...,False,False,True,False,False,False,True,False,False,True

## Выбор признаков

### Subtask:
Определите, какие столбцы будут использоваться для анализа или моделирования.

**Reasoning**:
Identify the numerical and one-hot encoded columns for analysis and modeling, excluding identifier columns.

In [16]:
# Identify columns suitable for analysis and modeling.
# Exclude 'user_id' as it is an identifier.
# All other numerical and one-hot encoded columns are suitable.
selected_features = [col for col in df.columns if col != 'user_id']

# Create a new DataFrame with selected features
df_selected = df[selected_features].copy()

print(f"Number of selected features: {len(selected_features)}")
display(df_selected.head())

Number of selected features: 414

,age,screen_time_hours,work_screen_hours,leisure_screen_hours,sleep_hours,sleep_quality_1_5,stress_level_0_10,productivity_0_100,exercise_minutes_per_week,social_hours_per_week,...,user_id_U0399,user_id_U0400,gender_Male,gender_Non-binary/Other,occupation_Retired,occupation_Self-employed,occupation_Student,occupation_Unemployed,work_mode_In-person,work_mode_Remote
0,33,10.79,5.44,5.35,6.63,1.0,9.3,44.7,127,0.7,...,False,False,False,False,False,False,False,False,False,True
1,28,7.40,0.37,7.03,8.05,3.0,5.7,78.0,74,2.1,...,False,False,False,False,False,False,False,False,True,False
2,35,9.78,1.09,8.69,6.48,1.0,9.1,51.8,67,8.0,...,False,False,False,False,False,False,False,False,False,False
3,42,11.13,0.56,10.57,6.89,1.0,10.0,37.0,0,5.7,...,False,False,True,False,False,False,False,False,False,False
4,28,13.22,4.09,9.13,5.79,1.0,10.0,38.5,143,10.1,...,False,False,True,False,False,False,True,False,False,True

## Масштабирование данных

### Subtask:
Примените масштабирование к числовым признакам, если это требуется для выбранных алгоритмов.

**Reasoning**:
Apply standard scaling to the numerical features in the `df_selected` DataFrame as required for selected algorithms.

In [17]:
from sklearn.preprocessing import StandardScaler

# Instantiate a StandardScaler object
scaler = StandardScaler()

# Fit the scaler to the df_selected DataFrame and transform it
df_scaled = scaler.fit_transform(df_selected)

# Convert the scaled NumPy array back to a DataFrame with original column names
df_scaled = pd.DataFrame(df_scaled, columns=df_selected.columns)

# Display the first few rows of the df_scaled DataFrame
display(df_scaled.head())

,age,screen_time_hours,work_screen_hours,leisure_screen_hours,sleep_hours,sleep_quality_1_5,stress_level_0_10,productivity_0_100,exercise_minutes_per_week,social_hours_per_week,...,user_id_U0399,user_id_U0400,gender_Male,gender_Non-binary/Other,occupation_Retired,occupation_Self-employed,occupation_Student,occupation_Unemployed,work_mode_In-person,work_mode_Remote
0,0.432159,0.709940,1.682008,-0.670210,-0.450077,-0.612204,0.551481,-0.640379,0.245854,-1.469361,...,-0.050063,-0.050063,-0.850963,-0.142857,-0.190445,-0.356034,-0.604308,-0.269047,-0.592749,1.304877
1,-0.238375,-0.656857,-0.940095,0.086915,1.217853,2.452668,-1.168709,1.579433,-0.512161,-1.183850,...,-0.050063,-0.050063,-0.850963,-0.142857,-0.190445,-0.356034,-0.604308,-0.269047,1.687055,-0.766356
2,0.700373,0.302723,-0.567726,0.835026,-0.626267,-0.612204,0.455915,-0.167086,-0.612276,0.019374,...,-0.050063,-0.050063,-0.850963,-0.142857,-0.190445,-0.356034,-0.604308,-0.269047,-0.592749,-0.766356
3,1.639121,0.847023,-0.841831,1.682285,-0.144681,-0.612204,0.885963,-1.153669,-1.570521,-0.449680,...,-0.050063,-0.050063,1.175139,-0.142857,-0.190445,-0.356034,-0.604308,-0.269047,-0.592749,-0.766356
4,-0.238375,1.689679,0.983815,1.033321,-1.436740,-0.612204,0.885963,-1.053678,0.474689,0.447640,...,-0.050063,-0.050063,1.175139,-0.142857,-0.190445,-0.356034,1.654786,-0.269047,-0.592749,1.304877

## Разделение данных

### Subtask:
Разделите данные на обучающую и тестовую выборки.

**Reasoning**:
Split the scaled data into training and testing sets.

In [18]:
from sklearn.model_selection import train_test_split

# Define features (X) for splitting. Since this is likely an unsupervised task or
# the target isn't specified yet, we split the entire scaled dataframe.
X = df_scaled

# Split the data into training and testing sets
X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)

# Print the shapes of the resulting training and testing sets
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)

Shape of X_train: (320, 414)
Shape of X_test: (80, 414)

## Разделение данных

### Разделите данные на обучающую и тестовую выборки.

**Reasoning**:
Split the scaled data into training and testing sets.

In [25]:
from sklearn.model_selection import train_test_split

# Define features (X) for splitting. Since this is likely an unsupervised task or
# the target isn't specified yet, we split the entire scaled dataframe.
X = df_scaled

# Split the data into training and testing sets
X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)

# Print the shapes of the resulting training and testing sets
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)

Shape of X_train: (320, 414)
Shape of X_test: (80, 414)

## Масштабирование данных

### Примените масштабирование к числовым признакам, если это требуется для выбранных алгоритмов.

In [24]:
from sklearn.preprocessing import StandardScaler

# Instantiate a StandardScaler object
scaler = StandardScaler()

# Fit the scaler to the df_selected DataFrame and transform it
df_scaled = scaler.fit_transform(df_selected)

# Convert the scaled NumPy array back to a DataFrame with original column names
df_scaled = pd.DataFrame(df_scaled, columns=df_selected.columns)

# Display the first few rows of the df_scaled DataFrame
display(df_scaled.head())

,age,screen_time_hours,work_screen_hours,leisure_screen_hours,sleep_hours,sleep_quality_1_5,stress_level_0_10,productivity_0_100,exercise_minutes_per_week,social_hours_per_week,...,user_id_U0399,user_id_U0400,gender_Male,gender_Non-binary/Other,occupation_Retired,occupation_Self-employed,occupation_Student,occupation_Unemployed,work_mode_In-person,work_mode_Remote
0,0.432159,0.709940,1.682008,-0.670210,-0.450077,-0.612204,0.551481,-0.640379,0.245854,-1.469361,...,-0.050063,-0.050063,-0.850963,-0.142857,-0.190445,-0.356034,-0.604308,-0.269047,-0.592749,1.304877
1,-0.238375,-0.656857,-0.940095,0.086915,1.217853,2.452668,-1.168709,1.579433,-0.512161,-1.183850,...,-0.050063,-0.050063,-0.850963,-0.142857,-0.190445,-0.356034,-0.604308,-0.269047,1.687055,-0.766356
2,0.700373,0.302723,-0.567726,0.835026,-0.626267,-0.612204,0.455915,-0.167086,-0.612276,0.019374,...,-0.050063,-0.050063,-0.850963,-0.142857,-0.190445,-0.356034,-0.604308,-0.269047,-0.592749,-0.766356
3,1.639121,0.847023,-0.841831,1.682285,-0.144681,-0.612204,0.885963,-1.153669,-1.570521,-0.449680,...,-0.050063,-0.050063,1.175139,-0.142857,-0.190445,-0.356034,-0.604308,-0.269047,-0.592749,-0.766356
4,-0.238375,1.689679,0.983815,1.033321,-1.436740,-0.612204,0.885963,-1.053678,0.474689,0.447640,...,-0.050063,-0.050063,1.175139,-0.142857,-0.190445,-0.356034,1.654786,-0.269047,-0.592749,1.304877

## Выбор признаков

### Subtask:
Определите, какие столбцы будут использоваться для анализа или моделирования.

In [23]:
# Identify columns suitable for analysis and modeling.
# Exclude 'user_id' as it is an identifier and not a feature for modeling.
# All other numerical and one-hot encoded columns are suitable features.
selected_features = [col for col in df.columns if col != 'user_id']

# Create a new DataFrame with selected features to be used for scaling and splitting.
df_selected = df[selected_features].copy()

print(f"Number of selected features: {len(selected_features)}")
# Display the first few rows of the DataFrame with selected features.
display(df_selected.head())

Number of selected features: 414

,age,screen_time_hours,work_screen_hours,leisure_screen_hours,sleep_hours,sleep_quality_1_5,stress_level_0_10,productivity_0_100,exercise_minutes_per_week,social_hours_per_week,...,user_id_U0399,user_id_U0400,gender_Male,gender_Non-binary/Other,occupation_Retired,occupation_Self-employed,occupation_Student,occupation_Unemployed,work_mode_In-person,work_mode_Remote
0,33,10.79,5.44,5.35,6.63,1.0,9.3,44.7,127,0.7,...,False,False,False,False,False,False,False,False,False,True
1,28,7.40,0.37,7.03,8.05,3.0,5.7,78.0,74,2.1,...,False,False,False,False,False,False,False,False,True,False
2,35,9.78,1.09,8.69,6.48,1.0,9.1,51.8,67,8.0,...,False,False,False,False,False,False,False,False,False,False
3,42,11.13,0.56,10.57,6.89,1.0,10.0,37.0,0,5.7,...,False,False,True,False,False,False,False,False,False,False
4,28,13.22,4.09,9.13,5.79,1.0,10.0,38.5,143,10.1,...,False,False,True,False,False,False,True,False,False,True

## Преобразование типов данных

### Subtask:
Преобразуйте строковые значения в числовые, если это необходимо для алгоритмов машинного обучения.

In [26]:
from google.colab import files

# Save the processed DataFrame to a CSV file
df.to_csv('processed_data.csv', index=False)

# Download the file to your local machine
files.download('processed_data.csv')

**Reasoning**:
Identify and convert categorical columns to numerical using one-hot encoding.

In [22]:
# Identify columns with object data types, which are typically categorical and need conversion for machine learning algorithms.
object_columns = df.select_dtypes(include=['object']).columns
print(f"Object columns to convert: {list(object_columns)}")

# Apply one-hot encoding to convert categorical columns into a numerical format.
# This creates new binary columns for each category. 'drop_first=True' prevents multicollinearity.
df = pd.get_dummies(df, columns=object_columns, drop_first=True)

# Display the first few rows of the updated DataFrame to see the result of one-hot encoding.
display(df.head())

Object columns to convert: []

,age,screen_time_hours,work_screen_hours,leisure_screen_hours,sleep_hours,sleep_quality_1_5,stress_level_0_10,productivity_0_100,exercise_minutes_per_week,social_hours_per_week,...,user_id_U0399,user_id_U0400,gender_Male,gender_Non-binary/Other,occupation_Retired,occupation_Self-employed,occupation_Student,occupation_Unemployed,work_mode_In-person,work_mode_Remote
0,33,10.79,5.44,5.35,6.63,1.0,9.3,44.7,127,0.7,...,False,False,False,False,False,False,False,False,False,True
1,28,7.40,0.37,7.03,8.05,3.0,5.7,78.0,74,2.1,...,False,False,False,False,False,False,False,False,True,False
2,35,9.78,1.09,8.69,6.48,1.0,9.1,51.8,67,8.0,...,False,False,False,False,False,False,False,False,False,False
3,42,11.13,0.56,10.57,6.89,1.0,10.0,37.0,0,5.7,...,False,False,True,False,False,False,False,False,False,False
4,28,13.22,4.09,9.13,5.79,1.0,10.0,38.5,143,10.1,...,False,False,True,False,False,False,True,False,False,True

## Очистка данных

### Subtask:
Обработайте пропущенные значения и некорректные данные.

**Reasoning**:
Examine the DataFrame for missing values, drop the column with only missing values, and clean the column names by removing leading/trailing spaces or special characters.

In [21]:
# Examine missing values
print("Missing values per column:")
print(df.isnull().sum())

# Drop the 'Unnamed: 15' column as it contains only missing values, if it exists.
if 'Unnamed: 15' in df.columns:
    df = df.drop('Unnamed: 15', axis=1)
    print("\nDataFrame after dropping 'Unnamed: 15' column:")
    display(df.head())
else:
    print("\n'Unnamed: 15' column not found. It might have been dropped already.")


# Clean column names by removing leading/trailing spaces and special characters like '\t'.
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace('\t', '')
print("\nCleaned column names:")
print(df.columns)

Missing values per column:
age                         0
screen_time_hours           2
work_screen_hours           3
leisure_screen_hours        1
sleep_hours                 0
                           ..
occupation_Self-employed    0
occupation_Student          0
occupation_Unemployed       0
work_mode_In-person         0
work_mode_Remote            0
Length: 414, dtype: int64

'Unnamed: 15' column not found. It might have been dropped already.

Cleaned column names:
Index(['age', 'screen_time_hours', 'work_screen_hours', 'leisure_screen_hours',
       'sleep_hours', 'sleep_quality_1_5', 'stress_level_0_10',
       'productivity_0_100', 'exercise_minutes_per_week',
       'social_hours_per_week',
       ...
       'user_id_U0399', 'user_id_U0400', 'gender_Male',
       'gender_Non-binary/Other', 'occupation_Retired',
       'occupation_Self-employed', 'occupation_Student',
       'occupation_Unemployed', 'work_mode_In-person', 'work_mode_Remote'],
      dtype='object', length=414)

## Загрузка данных

### Subtask:
Убедитесь, что данные загружены в pandas DataFrame.

**Reasoning**:
Check if the variable `df` exists and is a pandas DataFrame, then display the head and info of the dataframe.

In [19]:
import pandas as pd

# Проверяем, загружен ли DataFrame и является ли он объектом pandas DataFrame.
if 'df' in globals() and isinstance(df, pd.DataFrame):
    print("DataFrame 'df' загружен успешно.")
    # Отображаем первые 5 строк DataFrame для быстрого просмотра данных.
    display(df.head())
    # Выводим информацию о DataFrame, включая типы данных и количество непропущенных значений.
    df.info()
else:
    print("DataFrame 'df' не найден или не является pandas DataFrame.")

DataFrame 'df' загружен успешно.

,age,screen_time_hours,work_screen_hours,leisure_screen_hours,sleep_hours,sleep_quality_1_5,stress_level_0_10,productivity_0_100,exercise_minutes_per_week,social_hours_per_week,...,user_id_U0399,user_id_U0400,gender_Male,gender_Non-binary/Other,occupation_Retired,occupation_Self-employed,occupation_Student,occupation_Unemployed,work_mode_In-person,work_mode_Remote
0,33,10.79,5.44,5.35,6.63,1.0,9.3,44.7,127,0.7,...,False,False,False,False,False,False,False,False,False,True
1,28,7.40,0.37,7.03,8.05,3.0,5.7,78.0,74,2.1,...,False,False,False,False,False,False,False,False,True,False
2,35,9.78,1.09,8.69,6.48,1.0,9.1,51.8,67,8.0,...,False,False,False,False,False,False,False,False,False,False
3,42,11.13,0.56,10.57,6.89,1.0,10.0,37.0,0,5.7,...,False,False,True,False,False,False,False,False,False,False
4,28,13.22,4.09,9.13,5.79,1.0,10.0,38.5,143,10.1,...,False,False,True,False,False,False,True,False,False,True

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Columns: 414 entries, age to work_mode_Remote
dtypes: bool(403), float64(9), int64(2)
memory usage: 191.9 KB